spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sci.escom.noreply@gmail.com
    password: postgres
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
    properties:
        mail:
          from: <sci.escom.noreply@gmail.com>
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto_CI
    password: postgres
    username: postgres
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false #Para no tener que reiniciar el server cada que cambian los template
  servlet:
    multipart:
      max-file-size: 100MB #Esta cosa controla el tama√±o de los archivos que se pueden subir
      max-request-size: 100MB
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: TRACE